export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST'
export const CART_SAVE_SHIPPING_ADDRESS_REQUEST = 'CART_SAVE_SHIPPING_ADDRESS_REQUEST'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'